package com.technico.technicoproject.dto;

public enum ResponseStatus {
    SUCCESS,
    OWNER_NOT_CREATED,
    OWNER_NOT_FOUND,
    OWNER_NOT_UPDATED,
    OWNER_NOT_DELETED,
    PROPERTY_NOT_CREATED,
    PROPERTY_NOT_FOUND,
    PROPERTY_NOT_UPDATED,
    PROPERTY_NOT_DELETED,
    REPAIR_NOT_CREATED,
    REPAIR_NOT_FOUND,
    REPAIR_NOT_UPDATED,
    REPAIR_NOT_DELETED,
}
